// In-Memory Database Fallback for Offline/Local Edge Demonstrations

export let mockMachines = [
  {
    _id: 'm1',
    name: 'Conveyor Belt C-101',
    type: 'Mechanical Drive',
    status: 'Operational',
    temperature: 38.4,
    pressure: 1.2,
    vibration: 2.1,
    efficiency: 98,
    operator: 'H. Miller',
    lastMaintenance: new Date(),
  },
  {
    _id: 'm2',
    name: 'Hydraulic Press H-202',
    type: 'Fluid Mechanics',
    status: 'Maintenance',
    temperature: 55.2,
    pressure: 120.5,
    vibration: 5.6,
    efficiency: 85,
    operator: 'A. Patel',
    lastMaintenance: new Date(),
  },
  {
    _id: 'm3',
    name: 'Rotary Kiln R-303',
    type: 'Thermal Furnace',
    status: 'Operational',
    temperature: 850.0,
    pressure: 0.8,
    vibration: 1.8,
    efficiency: 94,
    operator: 'R. Davis',
    lastMaintenance: new Date(),
  },
  {
    _id: 'm4',
    name: 'Cooling Tower T-404',
    type: 'Heat Exchange',
    status: 'Offline',
    temperature: 15.1,
    pressure: 0.2,
    vibration: 12.4,
    efficiency: 0,
    operator: 'Unassigned',
    lastMaintenance: new Date(),
  },
  {
    _id: 'm5',
    name: 'Steam Boiler B-505',
    type: 'Thermal Boiler',
    status: 'Operational',
    temperature: 195.8,
    pressure: 15.4,
    vibration: 2.9,
    efficiency: 91,
    operator: 'S. Kovich',
    lastMaintenance: new Date(),
  },
];

export let mockTickets = [
  {
    _id: 't1',
    title: 'Vibration Anomaly Inspection',
    description: 'Vibration index on Cooling Tower T-404 exceeds threshold limit (10.0 mm/s). Inspect turbine blade balance.',
    machine: 'Cooling Tower T-404',
    severity: 'High',
    status: 'Open',
    createdAt: new Date(),
  },
  {
    _id: 't2',
    title: 'Seal Replacement H-202',
    description: 'Hydraulic oil weep at main cylinder seal. Schedule gasket replacement package.',
    machine: 'Hydraulic Press H-202',
    severity: 'Medium',
    status: 'In Progress',
    createdAt: new Date(),
  },
  {
    _id: 't3',
    title: 'Calibrate Kiln Temp Sensors',
    description: 'Re-zero thermocouple sensors during scheduled downtime shift.',
    machine: 'Rotary Kiln R-303',
    severity: 'Low',
    status: 'Open',
    createdAt: new Date(),
  },
];

export let mockIncidents = [
  {
    _id: 'i1',
    title: 'Hydraulic Fluid Leakage',
    description: 'Minor hydraulic pool formed near H-202 foundation. Absorbent cleanup pad applied. Hazard area taped.',
    machine: 'Hydraulic Press H-202',
    severity: 'Medium',
    status: 'Reported',
    loggedBy: 'A. Patel',
    createdAt: new Date(),
  },
  {
    _id: 'i2',
    title: 'Emergency Override Trip',
    description: 'Belt C-101 stop cord pulled accidentally during logistics loading. Verified clear and reset manually.',
    machine: 'Conveyor Belt C-101',
    severity: 'Low',
    status: 'Resolved',
    loggedBy: 'H. Miller',
    createdAt: new Date(),
  },
];

export let mockCommandLogs = [];
