// Rule-based offline parsing grammar rules
export function parseIntentOffline(text) {
  const query = text.toLowerCase().trim();
  
  // Co-Pilot Confirm/Cancel intercepts
  if (query === 'confirm' || query === 'yes' || query === 'confirm submission') {
    return { intent: 'COPILOT_CONFIRM', target: null, feedback: 'Submitting drafted maintenance order' };
  }
  if (query === 'cancel' || query === 'no' || query === 'cancel ticket') {
    return { intent: 'COPILOT_CANCEL', target: null, feedback: 'Discarding drafted maintenance order' };
  }

  // Co-Pilot Compound Command intercept
  if (query.includes('abnormal vibration') || query.includes('copilot') || query.includes('co-pilot') || (query.includes('history') && query.includes('report') && query.includes('ticket'))) {
    let machine = 'Steam Boiler B-505';
    if (query.includes('boiler 101')) machine = 'Boiler 101';
    else if (query.includes('conveyor')) machine = 'Conveyor Belt A';

    return {
      intent: 'COPILOT_MODE',
      target: machine,
      data: {
        machine,
        issue: 'Severe anomalous vibration detected',
        ticketData: {
          title: 'Abnormal vibration alert',
          machine,
          severity: 'High',
          description: 'Auto-generated by AI Co-Pilot. Anomalous vibration reported: ' + text
        }
      },
      feedback: 'Co-Pilot engaged. Navigating telemetry, pulling logs, and drafting maintenance ticket.'
    };
  }
  
  if (query.includes('ticket') && (query.includes('raise') || query.includes('create') || query.includes('file') || query.includes('report'))) {
    let machine = 'Boiler 101';
    if (query.includes('boiler 505')) machine = 'Boiler 505';
    else if (query.includes('conveyor')) machine = 'Conveyor Belt A';

    let severity = 'Medium';
    if (query.includes('critical')) severity = 'Critical';
    else if (query.includes('high')) severity = 'High';
    else if (query.includes('low')) severity = 'Low';

    let title = 'Telemetry Leak Anomaly';
    if (query.includes('leak')) title = 'Pipe Leakage detected';
    else if (query.includes('overheat') || query.includes('temperature')) title = 'Overheating warning';
    else if (query.includes('vibration')) title = 'Severe vibration';

    return {
      intent: 'FORM_FILL',
      target: 'maintenance_ticket',
      data: { title, machine, severity, description: 'Voice reported: ' + text },
      feedback: `Filing ${severity} severity maintenance ticket on ${machine}`
    };
  }

  if (query.includes('pdf') || query.includes('open manual') || query.includes('view document')) {
    let target = 'emergency';
    if (query.includes('hydraulic') || query.includes('spill')) target = 'hydraulic';
    else if (query.includes('conveyor') || query.includes('calibration')) target = 'conveyor';
    
    return { intent: 'OPEN_PDF', target, feedback: 'Opening Safety SOP PDF document' };
  }

  if (query.startsWith('click ')) {
    const target = query.replace('click ', '').trim();
    return { intent: 'CLICK', target, feedback: `Clicking ${target}` };
  }

  if (query.includes('dashboard') || query.includes('home') || query.includes('main console')) {
    return { intent: 'NAVIGATE', target: '/app/dashboard', feedback: 'Opening Dashboard' };
  }
  if (query.includes('maintenance') || query.includes('work order') || query.includes('repair') || query.includes('report')) {
    return { intent: 'NAVIGATE', target: '/app/maintenance', feedback: 'Opening Maintenance Console' };
  }
  if (query.includes('machine') || query.includes('status') || query.includes('telemetry') || query.includes('gauges') || query.includes('boiler') || query.includes('conveyor') || query.includes('temp') || query.includes('vibrat')) {
    return { intent: 'NAVIGATE', target: '/app/machines', feedback: 'Opening Machine Status' };
  }
  if (query.includes('safety') || query.includes('manual') || query.includes('sop') || query.includes('procedure') || query.includes('shutdown') || query.includes('rules') || query.includes('emergency') || query.includes('stop button') || query.includes('isolation')) {
    return { intent: 'NAVIGATE', target: '/app/safety', feedback: 'Opening Safety Manuals' };
  }
  if (query.includes('inventory') || query.includes('stock') || query.includes('parts') || query.includes('spares') || query.includes('reorder')) {
    return { intent: 'NAVIGATE', target: '/app/inventory', feedback: 'Opening Inventory' };
  }
  if (query.includes('incident') || query.includes('hazard') || query.includes('accident') || query.includes('spill') || query.includes('leak') || query.includes('safety register')) {
    return { intent: 'NAVIGATE', target: '/app/incidents', feedback: 'Opening Incident Reports' };
  }
  if (query.includes('analytics') || query.includes('chart') || query.includes('graph') || query.includes('performance') || query.includes('latency')) {
    return { intent: 'NAVIGATE', target: '/app/analytics', feedback: 'Opening Analytics' };
  }
  if (query.includes('settings') || query.includes('config') || query.includes('setup') || query.includes('preferences') || query.includes('volume') || query.includes('threshold')) {
    return { intent: 'NAVIGATE', target: '/app/settings', feedback: 'Opening Settings' };
  }
  if (query.includes('scroll down') || query.includes('move down') || query.includes('go down')) {
    return { intent: 'SCROLL_DOWN', target: null, feedback: 'Scrolling Down' };
  }
  if (query.includes('scroll up') || query.includes('move up') || query.includes('go up')) {
    return { intent: 'SCROLL_UP', target: null, feedback: 'Scrolling Up' };
  }
  if (query.includes('go back') || query.includes('navigate back') || query.includes('previous')) {
    return { intent: 'GO_BACK', target: null, feedback: 'Going Back' };
  }
  
  // Search matching regex
  const searchMatch = query.match(/(?:search|find|query|check for)\s+(.+)/);
  if (searchMatch && searchMatch[1]) {
    const target = searchMatch[1].trim();
    return { intent: 'SEARCH', target, feedback: `Searching for ${target}` };
  }

  return { intent: 'UNKNOWN', target: null, feedback: `Command recognized: "${text}". Please clarify.` };
}

export const getSystemPrompt = (text) => `You are a Voice AI Agent for a factory HMI.
Translate natural language commands into DOM actions.

Supported formats:
1. {"intent": "NAVIGATE", "target": "/app/dashboard" | "/app/machines" | "/app/maintenance" | "/app/safety" | "/app/inventory" | "/app/incidents" | "/app/analytics" | "/app/settings", "feedback": "Opening [Target Name]"}
2. {"intent": "SCROLL_DOWN", "target": null, "feedback": "Scrolling Down"}
3. {"intent": "SCROLL_UP", "target": null, "feedback": "Scrolling Up"}
4. {"intent": "GO_BACK", "target": null, "feedback": "Going Back"}
5. {"intent": "SEARCH", "target": "search text", "feedback": "Searching for [text]"}
6. {"intent": "CLICK", "target": "button text to click", "feedback": "Clicking [target]"}
7. {"intent": "OPEN_PDF", "target": "emergency" | "hydraulic" | "conveyor", "feedback": "Opening safety manual PDF"}
8. {"intent": "FORM_FILL", "target": "maintenance_ticket", "data": {"title": "Title", "machine": "Boiler 505" | "Boiler 101" | "Conveyor Belt A", "severity": "Critical" | "High" | "Medium" | "Low", "description": "desc"}, "feedback": "Filing maintenance ticket"}
9. {"intent": "COPILOT_MODE", "target": "Steam Boiler B-505", "data": {"machine": "Steam Boiler B-505", "issue": "vibration", "ticketData": {"title": "Abnormal vibration alert", "machine": "Steam Boiler B-505", "severity": "High", "description": "Notes"}}, "feedback": "Engaging Co-Pilot"}
10. {"intent": "COPILOT_CONFIRM", "target": null, "feedback": "Confirming ticket"}
11. {"intent": "COPILOT_CANCEL", "target": null, "feedback": "Cancelling ticket"}
12. {"intent": "UNKNOWN", "target": null, "feedback": "Unrecognized command"}

Input: "${text}"
Output strictly valid JSON only.`;
